POST https://skate-buddy.josholaus.com/api/users/decode HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJuYW1lIjoib2lkYTIiLCJlbWFpbCI6Im9pZGEyQGdtYWlsLmNvbSIsInByb2ZpbGVwaWN0dXJlSWQiOm51bGwsImlhdCI6MTY0Mzg3NzEyMiwiZXhwIjoxNjU1NTQxMTIyfQ.KQvkU03afSm19CkXs8HPanbm55mAcMe2WnKaBsHrTJI
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJuYW1lIjoib2lkYTIiLCJlbWFpbCI6Im9pZGEyQGdtYWlsLmNvbSIsInByb2ZpbGVwaWN0dXJlSWQiOm51bGwsImlhdCI6MTY0Mzg3NzEyMiwiZXhwIjoxNjU1NTQxMTIyfQ.KQvkU03afSm19CkXs8HPanbm55mAcMe2WnKaBsHrTJI"
}